// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oficina.Infrastructure.DataAccess;

#nullable disable

namespace Oficina.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251127031623_AddInscricaoMunicipalLoja")]
    partial class AddInscricaoMunicipalLoja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContaUsuario", b =>
                {
                    b.Property<int>("ContasId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.HasKey("ContasId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("ContaUsuario");
                });

            modelBuilder.Entity("Oficina.Aggregates.ContaAggregates.PagamentoConta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.ToTable("PagamentoConta");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.ClienteAggregates.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClienteStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contatos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<Guid>("SexoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("Atualizado", "Oficina.Domain.Aggregates.ClienteAggregates.Cliente.Atualizado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Atualizado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Criado", "Oficina.Domain.Aggregates.ClienteAggregates.Cliente.Criado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Criado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("DataNascimento", "Oficina.Domain.Aggregates.ClienteAggregates.Cliente.DataNascimento#DataNascimento", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Valor");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Documento", "Oficina.Domain.Aggregates.ClienteAggregates.Cliente.Documento#Documento", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("Numero");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Email", "Oficina.Domain.Aggregates.ClienteAggregates.Cliente.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Principal")
                                .HasColumnType("bit");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(800)
                                .HasColumnType("nvarchar(800)")
                                .HasColumnName("Principal");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ClienteStatusId");

                    b.HasIndex("SexoId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.ContaAggregates.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ContaStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int?>("PlanoId")
                        .HasColumnType("int");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("Atualizado", "Oficina.Domain.Aggregates.ContaAggregates.Conta.Atualizado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Atualizado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Criado", "Oficina.Domain.Aggregates.ContaAggregates.Conta.Criado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Criado");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ContaStatusId");

                    b.HasIndex("PlanoId");

                    b.ToTable("Conta");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.LojaAggregates.Loja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaId")
                        .HasColumnType("int");

                    b.Property<string>("Contatos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("InscricaoMunicipal")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("LogoTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("Atualizado", "Oficina.Domain.Aggregates.LojaAggregates.Loja.Atualizado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Atualizado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Criado", "Oficina.Domain.Aggregates.LojaAggregates.Loja.Criado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Criado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Documento", "Oficina.Domain.Aggregates.LojaAggregates.Loja.Documento#Documento", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("Numero");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Loja");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.LojaAggregates.UsuarioLoja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LojaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("UsuarioLoja");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFaturamentoFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFaturamentoInicial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPrevisao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("OrdemServicoStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PagamentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VeiculoClienteId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Atualizado", "Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServico.Atualizado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Atualizado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Criado", "Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServico.Criado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Criado");
                        });

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("OrdemServicoStatusId")
                        .IsUnique();

                    b.HasIndex("PagamentoId");

                    b.HasIndex("VeiculoClienteId");

                    b.ToTable("OrdemServico");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServicoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OrdemServicoId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.ComplexProperty<Dictionary<string, object>>("Atualizado", "Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServicoItem.Atualizado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Atualizado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Criado", "Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServicoItem.Criado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Criado");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OrdemServicoId");

                    b.ToTable("OrdemServicoItem");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServicoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("int");

                    b.Property<Guid>("OrdemServicoTipoPagamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrdemServicoTipoPagamentoId");

                    b.ToTable("OrdemServicoPagamento");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.PlanoAggregates.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LimiteLojas")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<Guid>("PlanoStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlanoStatusId");

                    b.ToTable("Plano");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.ProdutoAggregates.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty<Dictionary<string, object>>("Atualizado", "Oficina.Domain.Aggregates.ProdutoAggregates.Categoria.Atualizado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Atualizado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Criado", "Oficina.Domain.Aggregates.ProdutoAggregates.Categoria.Criado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Criado");
                        });

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.ProdutoAggregates.PrecoLoja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.ComplexProperty<Dictionary<string, object>>("Atualizado", "Oficina.Domain.Aggregates.ProdutoAggregates.PrecoLoja.Atualizado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Atualizado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Criado", "Oficina.Domain.Aggregates.ProdutoAggregates.PrecoLoja.Criado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Criado");
                        });

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("PrecoLoja");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.ProdutoAggregates.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty<Dictionary<string, object>>("Atualizado", "Oficina.Domain.Aggregates.ProdutoAggregates.Produto.Atualizado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Atualizado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Criado", "Oficina.Domain.Aggregates.ProdutoAggregates.Produto.Criado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Criado");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.UsuarioAggregates.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contatos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<Guid>("SexoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoClass")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UsuarioPadrao")
                        .HasColumnType("bit");

                    b.ComplexProperty<Dictionary<string, object>>("Atualizado", "Oficina.Domain.Aggregates.UsuarioAggregates.Usuario.Atualizado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Atualizado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Criado", "Oficina.Domain.Aggregates.UsuarioAggregates.Usuario.Criado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Criado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("DataNascimento", "Oficina.Domain.Aggregates.UsuarioAggregates.Usuario.DataNascimento#DataNascimento", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Valor");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Documento", "Oficina.Domain.Aggregates.UsuarioAggregates.Usuario.Documento#Documento", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("Numero");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SexoId");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuario");

                    b.HasDiscriminator<string>("TipoClass").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.UsuarioAggregates.UsuarioContexto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaId")
                        .HasColumnType("int");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContaId")
                        .IsUnique();

                    b.HasIndex("LojaId")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioContexto");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.VeiculoAggregates.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Hodrometro")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Montadora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Motorizacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.ComplexProperty<Dictionary<string, object>>("Atualizado", "Oficina.Domain.Aggregates.VeiculoAggregates.Veiculo.Atualizado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Atualizado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Criado", "Oficina.Domain.Aggregates.VeiculoAggregates.Veiculo.Criado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Criado");
                        });

                    b.HasKey("Id");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.VeiculoAggregates.VeiculoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Atualizado", "Oficina.Domain.Aggregates.VeiculoAggregates.VeiculoCliente.Atualizado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Atualizado");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Criado", "Oficina.Domain.Aggregates.VeiculoAggregates.VeiculoCliente.Criado#DataHora", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("Criado");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("VeiculoCliente");
                });

            modelBuilder.Entity("Oficina.Domain.Enumerations.DadoDominio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Dominio")
                        .IsUnique();

                    b.ToTable("DadoDominio");

                    b.HasDiscriminator<string>("Dominio").HasValue("DadoDominio");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.UsuarioAggregates.Funcionario", b =>
                {
                    b.HasBaseType("Oficina.Domain.Aggregates.UsuarioAggregates.Usuario");

                    b.HasDiscriminator().HasValue("Funcionario");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.UsuarioAggregates.SuperAdmin", b =>
                {
                    b.HasBaseType("Oficina.Domain.Aggregates.UsuarioAggregates.Usuario");

                    b.HasDiscriminator().HasValue("SuperAdmin");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.ClienteAggregates.ClienteStatus", b =>
                {
                    b.HasBaseType("Oficina.Domain.Enumerations.DadoDominio");

                    b.HasDiscriminator().HasValue("ClienteStatus");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.ContaAggregates.ContaStatus", b =>
                {
                    b.HasBaseType("Oficina.Domain.Enumerations.DadoDominio");

                    b.HasDiscriminator().HasValue("ContaStatus");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServicoStatus", b =>
                {
                    b.HasBaseType("Oficina.Domain.Enumerations.DadoDominio");

                    b.HasDiscriminator().HasValue("OrdemServicoStatus");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServicoTipoPagamento", b =>
                {
                    b.HasBaseType("Oficina.Domain.Enumerations.DadoDominio");

                    b.HasDiscriminator().HasValue("OrdemServicoTipoPagamento");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.PlanoAggregates.PlanoStatus", b =>
                {
                    b.HasBaseType("Oficina.Domain.Enumerations.DadoDominio");

                    b.HasDiscriminator().HasValue("PlanoStatus");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.UsuarioAggregates.Sexo", b =>
                {
                    b.HasBaseType("Oficina.Domain.Enumerations.DadoDominio");

                    b.HasDiscriminator().HasValue("Sexo");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.UsuarioAggregates.TipoDocumento", b =>
                {
                    b.HasBaseType("Oficina.Domain.Enumerations.DadoDominio");

                    b.HasDiscriminator().HasValue("TipoDocumento");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.UsuarioAggregates.TipoUsuario", b =>
                {
                    b.HasBaseType("Oficina.Domain.Enumerations.DadoDominio");

                    b.HasDiscriminator().HasValue("TipoUsuario");
                });

            modelBuilder.Entity("ContaUsuario", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.ContaAggregates.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oficina.Domain.Aggregates.UsuarioAggregates.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oficina.Aggregates.ContaAggregates.PagamentoConta", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.ContaAggregates.Conta", "Conta")
                        .WithMany("Pagamentos")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.ClienteAggregates.Cliente", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.ClienteAggregates.ClienteStatus", "ClienteStatus")
                        .WithMany()
                        .HasForeignKey("ClienteStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Oficina.Domain.Aggregates.UsuarioAggregates.Sexo", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Oficina.Domain.Aggregates.UsuarioAggregates.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClienteStatus");

                    b.Navigation("Sexo");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.ContaAggregates.Conta", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.ContaAggregates.ContaStatus", "Status")
                        .WithMany()
                        .HasForeignKey("ContaStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Oficina.Domain.Aggregates.PlanoAggregates.Plano", "Plano")
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Plano");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.LojaAggregates.Loja", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.ContaAggregates.Conta", "Conta")
                        .WithMany("Lojas")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oficina.Domain.Aggregates.UsuarioAggregates.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.LojaAggregates.UsuarioLoja", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.LojaAggregates.Loja", null)
                        .WithMany("UsuariosLoja")
                        .HasForeignKey("LojaId");

                    b.OwnsOne("Oficina.Domain.ValueObjects.DataHora", "Atualizado", b1 =>
                        {
                            b1.Property<int>("UsuarioLojaId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2");

                            b1.HasKey("UsuarioLojaId");

                            b1.ToTable("UsuarioLoja");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioLojaId");
                        });

                    b.OwnsOne("Oficina.Domain.ValueObjects.DataHora", "Criado", b1 =>
                        {
                            b1.Property<int>("UsuarioLojaId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2");

                            b1.HasKey("UsuarioLojaId");

                            b1.ToTable("UsuarioLoja");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioLojaId");
                        });

                    b.Navigation("Atualizado")
                        .IsRequired();

                    b.Navigation("Criado")
                        .IsRequired();
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServico", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.UsuarioAggregates.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServicoStatus", "OrdemServicoStatus")
                        .WithOne()
                        .HasForeignKey("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServico", "OrdemServicoStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServicoPagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId");

                    b.HasOne("Oficina.Domain.Aggregates.VeiculoAggregates.VeiculoCliente", "VeiculoCliente")
                        .WithMany()
                        .HasForeignKey("VeiculoClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("OrdemServicoStatus");

                    b.Navigation("Pagamento");

                    b.Navigation("VeiculoCliente");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServicoItem", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServico", null)
                        .WithMany("Itens")
                        .HasForeignKey("OrdemServicoId");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServicoPagamento", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServicoTipoPagamento", "OrdemServicoTipoPagamento")
                        .WithMany()
                        .HasForeignKey("OrdemServicoTipoPagamentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OrdemServicoTipoPagamento");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.PlanoAggregates.Plano", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.PlanoAggregates.PlanoStatus", "PlanoStatus")
                        .WithMany()
                        .HasForeignKey("PlanoStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PlanoStatus");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.ProdutoAggregates.PrecoLoja", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.LojaAggregates.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oficina.Domain.Aggregates.ProdutoAggregates.Produto", "Produto")
                        .WithMany("PrecoLojas")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.ProdutoAggregates.Produto", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.ProdutoAggregates.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.UsuarioAggregates.Usuario", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.UsuarioAggregates.Sexo", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Oficina.Domain.Aggregates.UsuarioAggregates.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oficina.Domain.Aggregates.UsuarioAggregates.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sexo");

                    b.Navigation("TipoDocumento");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.UsuarioAggregates.UsuarioContexto", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.ContaAggregates.Conta", "Conta")
                        .WithOne()
                        .HasForeignKey("Oficina.Domain.Aggregates.UsuarioAggregates.UsuarioContexto", "ContaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Oficina.Domain.Aggregates.LojaAggregates.Loja", "Loja")
                        .WithOne()
                        .HasForeignKey("Oficina.Domain.Aggregates.UsuarioAggregates.UsuarioContexto", "LojaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Oficina.Domain.Aggregates.UsuarioAggregates.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("Loja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.VeiculoAggregates.VeiculoCliente", b =>
                {
                    b.HasOne("Oficina.Domain.Aggregates.ClienteAggregates.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oficina.Domain.Aggregates.VeiculoAggregates.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.ContaAggregates.Conta", b =>
                {
                    b.Navigation("Lojas");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.LojaAggregates.Loja", b =>
                {
                    b.Navigation("UsuariosLoja");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.OrdemServicoAggregates.OrdemServico", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Oficina.Domain.Aggregates.ProdutoAggregates.Produto", b =>
                {
                    b.Navigation("PrecoLojas");
                });
#pragma warning restore 612, 618
        }
    }
}
